books/urls.py
from django.conf.urls import url

from .views import authors, books


app_name = "books"
urlpatterns = [
    url(r"^books/$", books, name="books"),
    url(r"^authors/$", authors, name="authors")
]

stylindex/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('books.urls', namespace='books_app')),
    url(r'^admin/', admin.site.urls),
]

books/models.py
from django.db import models


class Author(models.Model):
    name = models.CharField(max_length=250, unique=True)

    def __str__(self):
        return self.name


class Book(models.Model):
    book_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=250)
    isbn = models.CharField(max_length=16, unique=True)
    published_at = models.DateField()
    authors = models.ManyToManyField(Author)
    cover = models.URLField(max_length=200)

    def __str__(self):
        return self.name

books/views.py
from django.shortcuts import render
from .services import AuthorService, BookService


def order_values_validation(order):
    valid_order_options = ['name', '-name', 'published_at', '-published_at']
    if order in valid_order_options:
        return order
    return None


def books(request):
    """
    Render view with all books.

    Accepts ordering (ascending and descending) for
    book name and publish date fields only.

    Orders books by 'id' (default). This means that
    if a user tries to pass an order value other than
    'name' or 'published_at' directly through
    the url, ignores that order request and render books
    ordered by the default value 'id'.
    """
    order = request.GET.get('order', None)
    order = order_values_validation(order)
    books_qs = BookService.get_all()

    if order:
        books_qs = books_qs.order_by(order)
    context = {'books': books_qs}

    return render(request, 'books/books.html', context)


def authors(request):
    """
    Render view with all authors and all books
    associated with each author, example:

    Author: John
    Books: "Wunsch ThurmanVille", "Hintz LeathaVille"
    """
    authors = AuthorService.get_all()
    context = {'authors': authors}

    return render(request, 'books/authors.html', context)

books/templates/books/authors.html
{% extends "books/base.html" %}

{% block page %}
  {% for author in authors %}
    <ul>
      <li>
        <label>ID</label>
        {{ author.id }}
      </li>
      <li>
        <label>Author:</label>
        {{ author.name }}
      </li>
      <li>
        <label>Books:</label>
        {% for book in author.book_set.all %}
          "{{ book.name }}"{% if not forloop.last %}, {% endif %}
        {% endfor %}
      </li>
    </ul>
  {% endfor %}
{% endblock page %}

books/templates/books/base.html
{% extends "base.html" %}
{% load static %}

{% block app_content %}
  <nav>
    <h3>Menu</h3>
    <div class='menu'>
      <ul>
        <li><a href="{% url 'books:books' %}">Books</a></li>
        <li><a href="{% url 'books:authors' %}">Authors</a></li>
      </ul>
    </div>
    {% block ordering %}
    {% endblock ordering %}
  </nav>
  <div class='page-content'>
    {% block page %}
    {% endblock page %}
  </div>
{% endblock app_content %}

books/templates/books/books.html
{% extends "books/base.html" %}
{% load static %}

{% block ordering %}
<div class="dropdown">
  <h3>Order By</h3>
  <ul class="dropdown-menu">
    <li><a href="?order=name">Name (a-z)</a></li>
    <li><a href="?order=-name">Name (z-a)</a></li>
    <li><a href="?order=published_at">Date (ascending)</a></li>
    <li><a href="?order=-published_at">Date (descending)</a></li>
  </ul>
</div>
{% endblock ordering %}

{% block page %}
  {% for book in books %}
    <ul>
      <li>
        <label>ID:</label>
        {{ book.book_id }}
      </li>
      <li>
        <label>Name:</label>
        {{ book.name }}
      </li>
      <li>
        <label>ISBN:</label>
        {{ book.isbn }}
      </li>
      <li>
        <label>Published:</label>
        {{ book.published_at }}
      </li>
      <li>
        <label>Cover:</label>
        <a href="{{ book.cover }}">{{ book.cover }}</a>
      </li>
    </ul>
  {% endfor %}
{% endblock page %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>Stylindex</title>
</head>
{% block extra_links %}
{% endblock extra_links %}
<body>
    {% block app_content %}
    {% endblock app_content %}
</body>
</html>